import os

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from reportlab.lib import enums


REPORTS_DIR = "reports"


def generate_pdf(
    company: str,
    report: str
) -> str:

    os.makedirs(
        REPORTS_DIR,
        exist_ok=True
    )

    filename = (
        f"{company.replace(' ', '_')}"
        "_Investment_Report.pdf"
    )

    pdf_path = os.path.join(
        REPORTS_DIR,
        filename
    )

    doc = SimpleDocTemplate(
        pdf_path
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]

    heading_style = styles["Heading2"]

    body_style = styles["BodyText"]

    body_style.alignment = (
        enums.TA_JUSTIFY
    )

    story = []

    # ------------------------
    # TITLE
    # ------------------------

    story.append(
    Paragraph(
        f"""
        {company} Investment Report
        <br/>
        <br/>
        Generated by FinSight with <3
        """,
        title_style
    )
)

    story.append(
        Spacer(1, 20)
    )

    # ------------------------
    # CONTENT
    # ------------------------

    sections = report.split("#")

    for section in sections:

        section = section.strip()

        if not section:
            continue

        lines = section.split("\n")

        title = lines[0].strip()

        content = "\n".join(
            lines[1:]
        ).strip()

        story.append(
            Paragraph(
                title,
                heading_style
            )
        )

        story.append(
            Spacer(1, 6)
        )

        story.append(
            Paragraph(
                content.replace(
                    "\n",
                    "<br/>"
                ),
                body_style
            )
        )

        story.append(
            Spacer(1, 12)
        )

    doc.build(story)

    return pdf_path